### ISSUE TITLE
Recursive Dir

### ISSUE THREAD

**Issue by Happy-Ferret** [b3log/header#1]
Hi. Discovered your tool fairly recently. Great little program!
Curious though. Is there any way to recursively add headers to not just the root directory but also all sub-directories?

**Comment by 88250** [comment]
You could use `**.go` pattern for files in all sub-directories, [here](https://github.com/b3log/pipe/blob/master/.header.json) is an example.

**Comment by Happy-Ferret** [comment]
Thanks.

Strangely, that didn't work on my machine. Might be a WSL (Windows Subsystem for Linux) specific issue.

I ended up having to manually append the wildcards down to the maximum depth of the directory tree.

i e 

```
        "*.go",
        "*/*.go",
        "*/*/*.go",
        "*/*/*/*.go",
        "*/*/*/*/*.go",
        "*/*/*/*/*/*.go"
```
